"""
Remove unwanted table and default value set for columns

Revision ID: 8014709130eb
Revises: 6ae9ca2cbefb
Create Date: 2018-04-24 15:04:16.238438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8014709130eb'
down_revision = '6ae9ca2cbefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(u'job_ibfk_2', 'job', type_='foreignkey')
    op.drop_table('samples1')
    op.create_foreign_key(None, 'job', 'samples', ['sample_id'], ['id'], ondelete='cascade')
    op.alter_column('samples', 'EGFR',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'IDH1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'IDH2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'TP53',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'cancer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'gender',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'metastatic_site',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'sample_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'site',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('samples', 'tissue_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'tissue_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'site',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'sample_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'metastatic_site',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'gender',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'cancer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'TP53',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'IDH2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'IDH1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('samples', 'EGFR',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(u'job_ibfk_2', 'job', 'samples1', ['sample_id'], ['id'], ondelete=u'CASCADE')
    op.create_table('samples1',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sample_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tissue_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('site', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('metastatic_site', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('cancer', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('EGFR', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('IDH1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('IDH2', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('TP53', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('age_in_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tumor_grade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tumor_stage', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
