"""
column created in job table

Revision ID: 79dd508cc442
Revises: 87952f08ca16
Create Date: 2018-05-24 17:06:42.857318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dd508cc442'
down_revision = '87952f08ca16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('de_method', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('dz_fc_threshold', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('dz_p_threshold', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('site', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'site')
    op.drop_column('job', 'dz_p_threshold')
    op.drop_column('job', 'dz_fc_threshold')
    op.drop_column('job', 'de_method')
    # ### end Alembic commands ###
