"""
Added column in job details

Revision ID: 49cd68ccfca5
Revises: 79dd508cc442
Create Date: 2018-05-28 14:50:07.298815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49cd68ccfca5'
down_revision = '79dd508cc442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'site')
    op.drop_column('job', 'disease')
    op.drop_column('job', 'dz_p_threshold')
    op.drop_column('job', 'de_method')
    op.drop_column('job', 'dz_fc_threshold')
    op.add_column('job_details', sa.Column('case_EGFR', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('case_IDH1', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('case_IDH2', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('case_TP53', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('case_age_in_year', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('case_cancer', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('case_gender', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('case_metastatic_site', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('case_sample_id', sa.TEXT(), nullable=True))
    op.add_column('job_details', sa.Column('case_site', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('case_tissue_type', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('case_tumor_grade', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('case_tumor_stage', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('choose_fda_drugs', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_EGFR', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_IDH1', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_IDH2', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_TP53', sa.Boolean(), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_age_in_year', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_cancer', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_gender', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_metastatic_site', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_sample_id', sa.TEXT(), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_site', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_tissue_type', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_tumor_grade', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('ctrl_tumor_stage', sa.String(length=100), nullable=True))
    op.add_column('job_details', sa.Column('database', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('de_method', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('debug', sa.String(length=10), nullable=True))
    op.add_column('job_details', sa.Column('disease_name', sa.String(length=200), nullable=True))
    op.add_column('job_details', sa.Column('dz_fc_threshold', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('dz_p_threshold', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('landmark', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('max_gene_size', sa.String(length=50), nullable=True))
    op.add_column('job_details', sa.Column('weight_cell_line', sa.String(length=10), nullable=True))
    op.drop_column('job_details', 'out_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_details', sa.Column('out_file', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=50), nullable=False))
    op.drop_column('job_details', 'weight_cell_line')
    op.drop_column('job_details', 'max_gene_size')
    op.drop_column('job_details', 'landmark')
    op.drop_column('job_details', 'dz_p_threshold')
    op.drop_column('job_details', 'dz_fc_threshold')
    op.drop_column('job_details', 'disease_name')
    op.drop_column('job_details', 'debug')
    op.drop_column('job_details', 'de_method')
    op.drop_column('job_details', 'database')
    op.drop_column('job_details', 'ctrl_tumor_stage')
    op.drop_column('job_details', 'ctrl_tumor_grade')
    op.drop_column('job_details', 'ctrl_tissue_type')
    op.drop_column('job_details', 'ctrl_site')
    op.drop_column('job_details', 'ctrl_sample_id')
    op.drop_column('job_details', 'ctrl_metastatic_site')
    op.drop_column('job_details', 'ctrl_gender')
    op.drop_column('job_details', 'ctrl_cancer')
    op.drop_column('job_details', 'ctrl_age_in_year')
    op.drop_column('job_details', 'ctrl_TP53')
    op.drop_column('job_details', 'ctrl_IDH2')
    op.drop_column('job_details', 'ctrl_IDH1')
    op.drop_column('job_details', 'ctrl_EGFR')
    op.drop_column('job_details', 'choose_fda_drugs')
    op.drop_column('job_details', 'case_tumor_stage')
    op.drop_column('job_details', 'case_tumor_grade')
    op.drop_column('job_details', 'case_tissue_type')
    op.drop_column('job_details', 'case_site')
    op.drop_column('job_details', 'case_sample_id')
    op.drop_column('job_details', 'case_metastatic_site')
    op.drop_column('job_details', 'case_gender')
    op.drop_column('job_details', 'case_cancer')
    op.drop_column('job_details', 'case_age_in_year')
    op.drop_column('job_details', 'case_TP53')
    op.drop_column('job_details', 'case_IDH2')
    op.drop_column('job_details', 'case_IDH1')
    op.drop_column('job_details', 'case_EGFR')
    op.add_column('job', sa.Column('dz_fc_threshold', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=50), nullable=True))
    op.add_column('job', sa.Column('de_method', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=50), nullable=True))
    op.add_column('job', sa.Column('dz_p_threshold', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=50), nullable=True))
    op.add_column('job', sa.Column('disease', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True))
    op.add_column('job', sa.Column('site', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
