"""
added to store graphs
might be depricated later

Revision ID: c5a1486d5d43
Revises: 92b1e33d53d7
Create Date: 2018-07-12 09:43:23.429675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a1486d5d43'
down_revision = '92b1e33d53d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_details', sa.Column('drug_graphs', sa.String(length=255), nullable=True))
    op.add_column('job_details', sa.Column('signature_graphs', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_details', 'signature_graphs')
    op.drop_column('job_details', 'drug_graphs')
    # ### end Alembic commands ###
