"""
portaluser, samples, job, job_details table created.

Revision ID: 87952f08ca16
Revises: 
Create Date: 2018-05-22 19:53:54.500625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87952f08ca16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portaluser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('organization', sa.String(length=50), nullable=True),
    sa.Column('isActivated', sa.Boolean(), nullable=True),
    sa.Column('loginTime', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('tissue_type', sa.String(length=50), nullable=False),
    sa.Column('site', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('metastatic_site', sa.String(length=10), nullable=False),
    sa.Column('cancer', sa.String(length=100), nullable=False),
    sa.Column('EGFR', sa.Boolean(), nullable=False),
    sa.Column('IDH1', sa.Boolean(), nullable=False),
    sa.Column('IDH2', sa.Boolean(), nullable=False),
    sa.Column('TP53', sa.Boolean(), nullable=False),
    sa.Column('age_in_year', sa.Integer(), nullable=True),
    sa.Column('tumor_grade', sa.String(length=100), nullable=True),
    sa.Column('tumor_stage', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creationTime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('disease', sa.String(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_save', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portaluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('out_file', sa.String(length=50), nullable=False),
    sa.Column('creationTime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_details')
    op.drop_table('job')
    op.drop_table('samples')
    op.drop_table('portaluser')
    # ### end Alembic commands ###
