"""
job details table created to store output information after running the job

Revision ID: f8fc1bf50432
Revises: 3f7303291c0d
Create Date: 2018-03-09 11:48:15.192956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fc1bf50432'
down_revision = '3f7303291c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('out_file', sa.String(length=50), nullable=False),
    sa.Column('creationTime', sa.TIMESTAMP(), server_default='2018-03-09 11:48:15.067044', nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_details')
    # ### end Alembic commands ###
