"""
remove cancer column because value storing in disease_name column

Revision ID: 92b1e33d53d7
Revises: 49cd68ccfca5
Create Date: 2018-05-29 15:54:16.141916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92b1e33d53d7'
down_revision = '49cd68ccfca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_details', 'case_cancer')
    op.drop_column('job_details', 'ctrl_cancer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_details', sa.Column('ctrl_cancer', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=True))
    op.add_column('job_details', sa.Column('case_cancer', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
